site_name: PyAgenity
site_description: "A lightweight Python framework for building intelligent agents and multi-agent workflows on LiteLLM."
# Required for Material's instant navigation and previews
site_url: https://iamsdt.github.io/pyagenity/
repo_url: https://github.com/Iamsdt/PyAgenity
repo_name: Iamsdt/PyAgenity
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: null
  favicon: null
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - autorefs
  - section-index
  - mkdocstrings:
      enable_inventory: true
      default_handler: python
      handlers:
        python:
          paths: [.]  # ensure local package is discoverable
          options:
            # Docstrings & layout
            docstring_style: google
            docstring_section_style: table
            show_source: false
            group_by_category: true
            members_order: source
            filters: ["!^_[^_]"]
            show_if_no_docstring: false
            # Signatures
            separate_signature: true
            show_signature: true
            show_signature_annotations: true
            annotations_path: brief
            line_length: 80
            # Rendering details
            show_attribute_values: true
            show_bases: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting started:
      - getting-started/index.md
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Guides:
      - guides/callback-system.md
      - guides/custom-state.md
      - guides/dependency-injection.md
      - guides/logging.md
      - guides/pause-resume.md
      - guides/streaming.md
      - guides/unified-invoke.md
  - Tutorials:
      - tutorials/index.md
      - tutorials/callback-validation.md
      - tutorials/custom-state.md
      - tutorials/react-agent.md
      - tutorials/react-streaming.md
      - tutorials/react-mcp.md
      - tutorials/github-mcp.md
  - API Reference:
      - api/index.md
      - Graph: api/graph.md
      - Exceptions: api/exceptions.md
      - Publisher: api/publisher.md
      - State: api/state.md
      - Checkpointer: api/checkpointer.md
      - Utils: api/utils.md
  - Changelog: https://pypi.org/project/pyagenity/